In [2]:
import pandas as pd
import numpy as np
# from matplotlib import pyplot as plt
# import seaborn as sns
# %matplotlib inline
# from sklearn.feature_selection import RFE, f_regression
# #from sklearn.linear_model import (LinearRegression, Ridge, Lasso, RandomizedLasso)
# from sklearn.linear_model import (LinearRegression, Ridge)
# from sklearn.preprocessing import MinMaxScaler
# from sklearn.ensemble import RandomForestRegressor

In [6]:
dfBang = pd.read_csv ('D:\WD project\house-price-prediction\Dataset\Bangalore.csv')
dfChen = pd.read_csv ('D:\WD project\house-price-prediction\Dataset\Bangalore.csv')
dfDel = pd.read_csv ('D:\WD project\house-price-prediction\Dataset\Bangalore.csv')
dfHyd = pd.read_csv ('D:\WD project\house-price-prediction\Dataset\Bangalore.csv')
dfKol = pd.read_csv ('D:\WD project\house-price-prediction\Dataset\Bangalore.csv')
dfMum = pd.read_csv ('D:\WD project\house-price-prediction\Dataset\Bangalore.csv')

In [15]:
df.head(5)

,Price,Area,Location,No. of Bedrooms,Resale,MaintenanceStaff,Gymnasium,SwimmingPool,LandscapedGardens,JoggingTrack,...,BED,VaastuCompliant,Microwave,GolfCourse,TV,DiningTable,Sofa,Wardrobe,Refrigerator,city
0,30000000,3340,JP Nagar Phase 1,4,0,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,bangalore
1,7888000,1045,Dasarahalli on Tumkur Road,2,0,0,1,1,1,1,...,0,1,0,0,0,0,0,0,0,bangalore
2,4866000,1179,Kannur on Thanisandra Main Road,2,0,0,1,1,1,1,...,0,0,0,0,0,0,0,0,0,bangalore
3,8358000,1675,Doddanekundi,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,bangalore
4,6845000,1670,Kengeri,3,0,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,bangalore

In [13]:
df["city"] = "bangalore"

In [14]:
df["city"]

0       bangalore
1       bangalore
2       bangalore
3       bangalore
4       bangalore
          ...
6202    bangalore
6203    bangalore
6204    bangalore
6205    bangalore
6206    bangalore
Name: city, Length: 6207, dtype: object